### PR TITLE
Slavisa

### PR DESCRIPTION
**Pull request by sdjukic**
Code is almost alpha ready. All I have to do is allow users to upload/change their avatars. Password change implemented.

### CODE REVIEW

**Comment by afeld** [comment]
Pull requests are much easier to understand when they're small :wink: Add an inline comment if you want me to take a look at a particular section, but otherwise, go ahead and merge!

**Comment by afeld** [comment]
...and do any follow-up work in new short-lived branches.

**Comment by sdjukic** [comment]
Everything is pretty much straight forward. The only problem's that I have at the moment are:
every action is executed twice by server, I found out on the internet that turbolinks are to blamed I thought I disabled them in application.js, but seems it is not enough. 
Another problem is also about something happening twice. Any notification after an action is performed is shown twice. This is not such a big deal, all I have to do is dive into the code and find where I am showing notifications.

**Comment by afeld** [comment]
> every action is executed twice by server

You might want to add an Issue :smirk:

**Pull request merged**
