### PR TITLE
Raymond

### PR DESCRIPTION
**Pull request by RayFerr000**
Changed Readme

### CODE REVIEW

**Comment by afeld** [comment]
For starters, mind moving all the files up to the top level?

```bash
git mv NYTECH_project/* .
git mv NYTECH_project/.* .
```

**Comment by sdjukic** [comment]
Agree with Aidan.

**Comment by afeld** [comment]
No need to open a new pull request – just change the files on this branch and it will be updated.

**Comment by sdjukic** [comment]
Got it.

**Pull request merged**
